//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FASTService
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentStatu
    {
        public AssignmentStatu()
        {
            this.AssetAssignments = new HashSet<AssetAssignment>();
        }
    
        public int AssignmentStatusID { get; set; }
        public string StatusDescription { get; set; }
    
        public virtual ICollection<AssetAssignment> AssetAssignments { get; set; }
    }
}
