//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FASTService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.AccessRights = new HashSet<AccessRight>();
            this.Employees = new HashSet<Employee>();
        }
    
        public int DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public string GroupName { get; set; }
    
        public virtual ICollection<AccessRight> AccessRights { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
