//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FASTService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.AccessRights = new HashSet<AccessRight>();
            this.AssetAssignments = new HashSet<AssetAssignment>();
            this.AuditTrails = new HashSet<AuditTrail>();
            this.Registrations = new HashSet<Registration>();
        }
    
        public int EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public string Gender { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public int DepartmentID { get; set; }
        public int PositionID { get; set; }
        public short IsCompany { get; set; }
        public string CompanyName { get; set; }
        public short Status { get; set; }
    
        public virtual ICollection<AccessRight> AccessRights { get; set; }
        public virtual ICollection<AssetAssignment> AssetAssignments { get; set; }
        public virtual ICollection<AuditTrail> AuditTrails { get; set; }
        public virtual Department Department { get; set; }
        public virtual Position Position { get; set; }
        public virtual ICollection<Registration> Registrations { get; set; }
    }
}
